### ISSUE TITLE
ER diagram

### ISSUE THREAD

**Issue by inesmersak** [andrazdeluisa/NBA.stats#2]
Par pripomb na ER diagram:
* atribut Igralec pri _Ekipi_ zgleda odveč, ker imate relaciji _Igralec_ in _Ekipa_ že povezani z relacijo Igra;
* entiteti _Ekipa_ manjkata ime in primarni ključ (morda kratica?), lahko bi imeli tudi lokacijo;
* pri _Igralec_, _Lastnik_, _Trener_ je ime slaba izbira primarnega ključa, saj se brez težav zgodi, da obstajata dva igralca z istim imenom -- mislim, da je tukaj bolj smotrno imeti zgeneriran številčni ID, v primeru Postgresa tip SERIAL.

**Comment by andrazdeluisa** [comment]
Popravljeno v 68ff68c91d5bc99b0ed95fe3741b8510c49d667f
