### ISSUE TITLE
Mapa views

### ISSUE THREAD

**Issue by jaanos** [andrazdeluisa/NBA.stats#3]
Opažam, da imate na repozitoriju mapo `Views` (z veliko začetnico), medtem ko `bottle.py` privzeto išče predloge v mapi `views` (z malo začetnico). Na sistemih, kjer velikost črk v imenih datotek ni pomembna (Windows, Mac), to ne predstavlja težave, zato pa aplikacija ne bo delovala na sistemih, kjer velikost črk je pomembna (Linux in ostali Unixi). Zato svetujem, da mapo ustrezno preimenujete.

Možno je, da git ne bo zaznal spremembe, če boste samo spremenili velikost črk - v tem primeru spremenite ime v nekaj drugega, naredite commit (morda bo zadostoval `git add`, nisem prepričan), nato pa spremenite ime v `views` in znova naredite commit. 

Še to: na repozitoriju imate datoteke `Thumbs.db` in `.DS_Store` - te vanj ne sodijo, tako da jih pobrišite, poleg tega pa dodajte ustrezni vrstici v `.gitignore`, da jih ne boste po nesreči znova dodali.

**Comment by andrazdeluisa** [comment]
Hvala za nasvet. Popravljeno v commitu #63.

**Comment by jaanos** [comment]
Za sklicevanje na commite uporabite ustrezno šifro, v tem primeru 52b94bdb1fd1a01f7dc2172ea23b6b535bb52f4e. Lahko pa tudi v sporočilo ob commitu napišete npr. *Closes #3*, kjer je #3 številka issueja, da se ta zapre.
